### ISSUE TITLE
Input parameter parser

### ISSUE THREAD

**Issue by allaffa** [allaffa/CompetitiveGradientDescent#25]
It would be nice to have an input parser to automatize the import of important parameters at runtime. 
An example that we could mimic is described by the implementations in the following GitHub directory:
`https://github.com/eriklindernoren/PyTorch-GAN`

**Comment by vitst** [comment]
@allaffa, do you mean here an argument parser in `main_GANs.py`?

**Comment by allaffa** [comment]
@vitst 

yes, that is exactly what I had in mind

**Comment by vitst** [comment]
Great, I will work on this today then. I can use either `docopt` or `argparse`? Any preferences?

**Comment by allaffa** [comment]
@vitst 

I temporarily reverted the pull request after accepting it, because when I tried to run the code from the shell I could not make it correctly run. I was running the following command:

python3 main_GANs.py [--epochs=100] [--optimizer='CGD'] [--learning_rate=0.0005]

What am I doing wrong?

**Comment by allaffa** [comment]
@vitst 

> Great, I will work on this today then. I can use either `docopt` or `argparse`? Any preferences?

Which one of the two do you think is best? I was thinking about argparse, but I do not have necessarily any strong preference.

**Comment by vitst** [comment]
@allaffa, The square brackets show that the argument is optional, meaning there is a default value. It should be
`python3 main_GANs.py --epochs=100 --optimizer='CGD' --learning_rate=0.0005`
Also, uncomment the model to make it run (MLP_GANs  or DCGANs are both commented now) and provide `epochs`, `optimizer_name`, and `learning_rate` parameters to the model.

I think `docopt` is cleaner.

**Comment by allaffa** [comment]
@vitst  
Thank. Then let us go ahead with docopt.

**Comment by aprokop** [comment]
Closing as `docopt` works.
