### ISSUE TITLE
Abstract class for GANs_model 

### ISSUE THREAD

**Issue by allaffa** [allaffa/CompetitiveGradientDescent#26]
Right now, we have to implementations of the GANs model inside two Python scripts:
GANs_model.py ----> GANs with multi-layer perceptrons neural networks (MLP)
DCGANS_model.py ----> GANs with convolutional neural networks (CNN)

To better. structure the code, we could build an abstract class calls GANs_model and have the MLP and CNN variants be two classes that inherits from it. 

I would use the following nomenclature:

- Abstract class: **GANs_model** 

- MLP implementation of GANs: **MLP_GANs_model**

- CNN implementation of GANS: **DCGANs_model**

**Comment by allaffa** [comment]
@aprokop 

I tried to structure the code to minimize redundancy through class inheritance. 
When you have time, could you have a look at `GANs_abstract_object.py `, MLP_GANs_object and `DCGANs_object.py` and give me feedback?

Thanks.

**Comment by aprokop** [comment]
We should start doing PRs to receive feedback early :) Sure, I'll take a look.

**Comment by allaffa** [comment]
Thank you! Will sue PR from now on
